# Generated by Django 3.1.4 on 2021-01-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
